title: <p align ="center">Ravi Arepalli</p>
logo: /assets/img/Profile.png
description: Aspirated to be an AI ML expert in Public Safety
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
